-- MySQL Script generated by MySQL Workbench
-- Fri Jun  2 21:05:53 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bazar
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bazar
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bazar` DEFAULT CHARACTER SET utf8 ;
USE `bazar` ;

-- -----------------------------------------------------
-- Table `bazar`.`ROLES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bazar`.`ROLES` (
  `id_rol` INT(1) NOT NULL AUTO_INCREMENT,
  `rol_usuario` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bazar`.`REGIONES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bazar`.`REGIONES` (
  `id_regiones` INT(2) NOT NULL AUTO_INCREMENT,
  `nombre_region` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_regiones`),
  UNIQUE INDEX `nombre_region_UNIQUE` (`nombre_region` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bazar`.`COMUNAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bazar`.`COMUNAS` (
  `id_comuna` INT(2) NOT NULL AUTO_INCREMENT,
  `nombre_comuna` VARCHAR(30) NOT NULL,
  `region_FK` INT(2) NOT NULL,
  PRIMARY KEY (`id_comuna`),
  UNIQUE INDEX `nombre_comuna_UNIQUE` (`nombre_comuna` ASC) ,
  INDEX `fk_COMUNAS_REGIONES1_idx` (`region_FK` ASC) ,
  CONSTRAINT `fk_COMUNAS_REGIONES1`
    FOREIGN KEY (`region_FK`)
    REFERENCES `bazar`.`REGIONES` (`id_regiones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bazar`.`USUARIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bazar`.`USUARIOS` (
  `id_usuario` INT(2) NOT NULL AUTO_INCREMENT,
  `run_usuario` VARCHAR(10) NOT NULL,
  `clave_usuario` VARCHAR(64) NOT NULL,
  `nombre_usuario` VARCHAR(25) NOT NULL,
  `apellido_usuario` VARCHAR(25) NOT NULL,
  `rol_FK` INT(1) NOT NULL,
  `comuna_FK` INT(2) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `run_usuario_UNIQUE` (`run_usuario` ASC) ,
  INDEX `fk_USUARIOS_ROLES_idx` (`rol_FK` ASC) ,
  INDEX `fk_USUARIOS_COMUNAS1_idx` (`comuna_FK` ASC) ,
  CONSTRAINT `fk_USUARIOS_ROLES`
    FOREIGN KEY (`rol_FK`)
    REFERENCES `bazar`.`ROLES` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USUARIOS_COMUNAS1`
    FOREIGN KEY (`comuna_FK`)
    REFERENCES `bazar`.`COMUNAS` (`id_comuna`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bazar`.`TIPO_GIRO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bazar`.`TIPO_GIRO` (
  `id_giro` INT(2) NOT NULL AUTO_INCREMENT,
  `nombre_giro` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_giro`),
  UNIQUE INDEX `nombre_giro_UNIQUE` (`nombre_giro` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bazar`.`RAZON_SOCIAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bazar`.`RAZON_SOCIAL` (
  `id_razon_social` INT NOT NULL AUTO_INCREMENT,
  `razon_social` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_razon_social`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bazar`.`CLIENTES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bazar`.`CLIENTES` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `run_cliente` VARCHAR(10) NOT NULL,
  `nombre_cliente` VARCHAR(25) NOT NULL,
  `apellido_cliente` VARCHAR(25) NOT NULL,
  `direccion` VARCHAR(64) NOT NULL,
  `comuna_FK` INT(2) NOT NULL,
  `tipo_giro_FK` INT(2) NOT NULL,
  `razon_social_FK` INT NOT NULL,
  PRIMARY KEY (`id_cliente`),
  UNIQUE INDEX `run_cliente_UNIQUE` (`run_cliente` ASC) ,
  INDEX `fk_CLIENTES_COMUNAS1_idx` (`comuna_FK` ASC) ,
  INDEX `fk_CLIENTES_TIPO_GIRO1_idx` (`tipo_giro_FK` ASC) ,
  INDEX `fk_CLIENTES_RAZON_SOCIAL1_idx` (`razon_social_FK` ASC) ,
  CONSTRAINT `fk_CLIENTES_COMUNAS1`
    FOREIGN KEY (`comuna_FK`)
    REFERENCES `bazar`.`COMUNAS` (`id_comuna`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CLIENTES_TIPO_GIRO1`
    FOREIGN KEY (`tipo_giro_FK`)
    REFERENCES `bazar`.`TIPO_GIRO` (`id_giro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CLIENTES_RAZON_SOCIAL1`
    FOREIGN KEY (`razon_social_FK`)
    REFERENCES `bazar`.`RAZON_SOCIAL` (`id_razon_social`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bazar`.`MARCAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bazar`.`MARCAS` (
  `id_marca` INT(2) NOT NULL AUTO_INCREMENT,
  `nombre_marca` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id_marca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bazar`.`CATEGORIAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bazar`.`CATEGORIAS` (
  `id_categoria` INT(2) NOT NULL AUTO_INCREMENT,
  `nombre_categoria` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bazar`.`PRODUCTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bazar`.`PRODUCTOS` (
  `id_producto` INT(5) NOT NULL AUTO_INCREMENT,
  `codigo_producto` VARCHAR(45) NOT NULL,
  `nombre_producto` VARCHAR(40) NOT NULL,
  `precio_producto` INT(6) NOT NULL,
  `marca_FK` INT(2) NOT NULL,
  `usuario_FK` INT(2) NOT NULL,
  `categoria_FK` INT(2) NOT NULL,
  PRIMARY KEY (`id_producto`),
  INDEX `fk_PRODUCTOS_MARCAS1_idx` (`marca_FK` ASC) ,
  INDEX `fk_PRODUCTOS_USUARIOS1_idx` (`usuario_FK` ASC) ,
  INDEX `fk_PRODUCTOS_CATEGORIAS1_idx` (`categoria_FK` ASC) ,
  CONSTRAINT `fk_PRODUCTOS_MARCAS1`
    FOREIGN KEY (`marca_FK`)
    REFERENCES `bazar`.`MARCAS` (`id_marca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRODUCTOS_USUARIOS1`
    FOREIGN KEY (`usuario_FK`)
    REFERENCES `bazar`.`USUARIOS` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRODUCTOS_CATEGORIAS1`
    FOREIGN KEY (`categoria_FK`)
    REFERENCES `bazar`.`CATEGORIAS` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bazar`.`VENTAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bazar`.`VENTAS` (
  `id_venta` INT NOT NULL AUTO_INCREMENT,
  `fecha_emcion` DATETIME NOT NULL,
  `cliente_FK` INT NOT NULL,
  `usuario_FK` INT(2) NOT NULL,
  PRIMARY KEY (`id_venta`),
  INDEX `fk_VENTAS_CLIENTES1_idx` (`cliente_FK` ASC) ,
  INDEX `fk_VENTAS_USUARIOS1_idx` (`usuario_FK` ASC) ,
  CONSTRAINT `fk_VENTAS_CLIENTES1`
    FOREIGN KEY (`cliente_FK`)
    REFERENCES `bazar`.`CLIENTES` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VENTAS_USUARIOS1`
    FOREIGN KEY (`usuario_FK`)
    REFERENCES `bazar`.`USUARIOS` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bazar`.`FACTURAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bazar`.`FACTURAS` (
  `id_factura` INT NOT NULL AUTO_INCREMENT,
  `total_factura` INT(7) NOT NULL,
  `venta_FK` INT NOT NULL,
  PRIMARY KEY (`id_factura`),
  INDEX `fk_FACTURAS_VENTAS1_idx` (`venta_FK` ASC) ,
  CONSTRAINT `fk_FACTURAS_VENTAS1`
    FOREIGN KEY (`venta_FK`)
    REFERENCES `bazar`.`VENTAS` (`id_venta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bazar`.`DETALLE_FACTURAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bazar`.`DETALLE_FACTURAS` (
  `id_detalle_factura` INT NOT NULL AUTO_INCREMENT,
  `cantidad` INT(3) NOT NULL,
  `total` INT(7) NOT NULL,
  `producto_FK` INT(5) NOT NULL,
  `factura_FK` INT NOT NULL,
  PRIMARY KEY (`id_detalle_factura`),
  INDEX `fk_DETALLE_COMPRA_PRODUCTOS1_idx` (`producto_FK` ASC) ,
  INDEX `fk_DETALLE_COMPRA_FACTURAS1_idx` (`factura_FK` ASC) ,
  CONSTRAINT `fk_DETALLE_COMPRA_PRODUCTOS1`
    FOREIGN KEY (`producto_FK`)
    REFERENCES `bazar`.`PRODUCTOS` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DETALLE_COMPRA_FACTURAS1`
    FOREIGN KEY (`factura_FK`)
    REFERENCES `bazar`.`FACTURAS` (`id_factura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bazar`.`BOLETAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bazar`.`BOLETAS` (
  `id_boleta` INT NOT NULL AUTO_INCREMENT,
  `total_boleta` INT(7) NOT NULL,
  `venta_FK` INT NOT NULL,
  PRIMARY KEY (`id_boleta`),
  INDEX `fk_BOLETAS_VENTAS1_idx` (`venta_FK` ASC) ,
  CONSTRAINT `fk_BOLETAS_VENTAS1`
    FOREIGN KEY (`venta_FK`)
    REFERENCES `bazar`.`VENTAS` (`id_venta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bazar`.`DETALLE_BOLETAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bazar`.`DETALLE_BOLETAS` (
  `id_detalle_boleta` INT NOT NULL AUTO_INCREMENT,
  `cantidad` INT(3) NOT NULL,
  `total` INT(7) NOT NULL,
  `producto_FK` INT(5) NOT NULL,
  `boleta_FK` INT NOT NULL,
  PRIMARY KEY (`id_detalle_boleta`),
  INDEX `fk_DETALLE_COMPRA_PRODUCTOS1_idx` (`producto_FK` ASC) ,
  INDEX `fk_DETALLE_BOLETAS_BOLETAS1_idx` (`boleta_FK` ASC) ,
  CONSTRAINT `fk_DETALLE_COMPRA_PRODUCTOS10`
    FOREIGN KEY (`producto_FK`)
    REFERENCES `bazar`.`PRODUCTOS` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DETALLE_BOLETAS_BOLETAS1`
    FOREIGN KEY (`boleta_FK`)
    REFERENCES `bazar`.`BOLETAS` (`id_boleta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bazar`.`DATOS_EMPRESA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bazar`.`DATOS_EMPRESA` (
  `id_datos_empresa` INT NOT NULL AUTO_INCREMENT,
  `nombre_empresa` VARCHAR(40) NOT NULL,
  `rut_empresa` VARCHAR(10) NOT NULL,
  `direccion_empresa` VARCHAR(64) NOT NULL,
  `IVA` INT NOT NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`id_datos_empresa`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- -----------------------------------------------------
-- Insert Roles
-- -----------------------------------------------------
INSERT INTO `bazar`.`ROLES` (`rol_usuario`) VALUES
('JEFE DE VENTAS'),
('VENDEDOR');
-- -----------------------------------------------------
-- Insert Regiones
-- -----------------------------------------------------
INSERT INTO `bazar`.`REGIONES` (`nombre_region`) VALUES
('BIOBIO'),
('ÑUBLE'),
('CONCEPCIÓN'),
('MAULE'),
('ARAUCANÍA');
-- -----------------------------------------------------
-- Insert Comunas
-- -----------------------------------------------------
INSERT INTO `bazar`.`COMUNAS` (`nombre_comuna`, `region_FK`) VALUES
('CONCEPCION', 1),
('LOS ANGELES', 1),
('CHILLAN', 2),
('TEMUCO', 2),
('PUERTO MONTT', 3),
('VALDIVIA', 3),
('VINA DEL MAR', 4),
('VALPARAISO', 4),
('SANTIAGO', 5),
('RANCAGUA', 5);
-- -----------------------------------------------------
-- Insert Usuarios
-- -----------------------------------------------------
INSERT INTO `bazar`.`USUARIOS` (`run_usuario`, `clave_usuario`, `nombre_usuario`, `apellido_usuario`, `rol_FK`, `comuna_FK`) VALUES
('18505240-0', 'PASS1234', 'FERNANDO', 'ROSAS', 1, 3),
('12345678-9', 'PASS1234', 'JUAN', 'PEREZ', 2, 3),
('98765432-1', 'PASS1234', 'MARIA', 'LOPEZ', 2, 3),
('12345678-K', 'PASS1234', 'PEDRO', 'GARCIA', 2, 3),
('1234567-8', 'PASS1234', 'ANA', 'MARTINEZ', 2, 3);
-- -----------------------------------------------------
-- Insert 
-- -----------------------------------------------------