-- MySQL Script generated by MySQL Workbench
-- Fri Jun  9 17:34:10 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bazar
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bazar
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bazar` DEFAULT CHARACTER SET utf8 ;
USE `bazar` ;

-- -----------------------------------------------------
-- Table `bazar`.`ROLES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bazar`.`ROLES` (
  `id_rol` INT(1) NOT NULL AUTO_INCREMENT,
  `rol_usuario` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bazar`.`REGIONES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bazar`.`REGIONES` (
  `id_regiones` INT(2) NOT NULL AUTO_INCREMENT,
  `nombre_region` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_regiones`),
  UNIQUE INDEX `nombre_region_UNIQUE` (`nombre_region` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bazar`.`COMUNAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bazar`.`COMUNAS` (
  `id_comuna` INT(2) NOT NULL AUTO_INCREMENT,
  `nombre_comuna` VARCHAR(30) NOT NULL,
  `region_FK` INT(2) NOT NULL,
  PRIMARY KEY (`id_comuna`),
  UNIQUE INDEX `nombre_comuna_UNIQUE` (`nombre_comuna` ASC) ,
  INDEX `fk_COMUNAS_REGIONES1_idx` (`region_FK` ASC) ,
  CONSTRAINT `fk_COMUNAS_REGIONES1`
    FOREIGN KEY (`region_FK`)
    REFERENCES `bazar`.`REGIONES` (`id_regiones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bazar`.`USUARIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bazar`.`USUARIOS` (
  `id_usuario` INT(2) NOT NULL AUTO_INCREMENT,
  `run_usuario` VARCHAR(10) NOT NULL,
  `clave_usuario` VARCHAR(64) NOT NULL,
  `nombre_usuario` VARCHAR(25) NOT NULL,
  `apellido_usuario` VARCHAR(25) NOT NULL,
  `rol_FK` INT(1) NOT NULL,
  `comuna_FK` INT(2) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `run_usuario_UNIQUE` (`run_usuario` ASC) ,
  INDEX `fk_USUARIOS_ROLES_idx` (`rol_FK` ASC) ,
  INDEX `fk_USUARIOS_COMUNAS1_idx` (`comuna_FK` ASC) ,
  CONSTRAINT `fk_USUARIOS_ROLES`
    FOREIGN KEY (`rol_FK`)
    REFERENCES `bazar`.`ROLES` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USUARIOS_COMUNAS1`
    FOREIGN KEY (`comuna_FK`)
    REFERENCES `bazar`.`COMUNAS` (`id_comuna`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bazar`.`TIPO_GIRO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bazar`.`TIPO_GIRO` (
  `id_giro` INT(2) NOT NULL AUTO_INCREMENT,
  `nombre_giro` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_giro`),
  UNIQUE INDEX `nombre_giro_UNIQUE` (`nombre_giro` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bazar`.`RAZON_SOCIAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bazar`.`RAZON_SOCIAL` (
  `id_razon_social` INT NOT NULL AUTO_INCREMENT,
  `razon_social` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_razon_social`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bazar`.`CLIENTES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bazar`.`CLIENTES` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `run_cliente` VARCHAR(10) NOT NULL,
  `nombre_cliente` VARCHAR(25) NOT NULL,
  `apellido_cliente` VARCHAR(25) NOT NULL,
  `direccion` VARCHAR(64) NOT NULL,
  `comuna_FK` INT(2) NOT NULL,
  `tipo_giro_FK` INT(2) NOT NULL,
  `razon_social_FK` INT NOT NULL,
  `usuario_FK` INT(2) NOT NULL,
  PRIMARY KEY (`id_cliente`),
  UNIQUE INDEX `run_cliente_UNIQUE` (`run_cliente` ASC) ,
  INDEX `fk_CLIENTES_COMUNAS1_idx` (`comuna_FK` ASC) ,
  INDEX `fk_CLIENTES_TIPO_GIRO1_idx` (`tipo_giro_FK` ASC) ,
  INDEX `fk_CLIENTES_RAZON_SOCIAL1_idx` (`razon_social_FK` ASC) ,
  INDEX `fk_CLIENTES_USUARIOS1_idx` (`usuario_FK` ASC) ,
  CONSTRAINT `fk_CLIENTES_COMUNAS1`
    FOREIGN KEY (`comuna_FK`)
    REFERENCES `bazar`.`COMUNAS` (`id_comuna`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CLIENTES_TIPO_GIRO1`
    FOREIGN KEY (`tipo_giro_FK`)
    REFERENCES `bazar`.`TIPO_GIRO` (`id_giro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CLIENTES_RAZON_SOCIAL1`
    FOREIGN KEY (`razon_social_FK`)
    REFERENCES `bazar`.`RAZON_SOCIAL` (`id_razon_social`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CLIENTES_USUARIOS1`
    FOREIGN KEY (`usuario_FK`)
    REFERENCES `bazar`.`USUARIOS` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bazar`.`MARCAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bazar`.`MARCAS` (
  `id_marca` INT(2) NOT NULL AUTO_INCREMENT,
  `nombre_marca` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id_marca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bazar`.`CATEGORIAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bazar`.`CATEGORIAS` (
  `id_categoria` INT(2) NOT NULL AUTO_INCREMENT,
  `nombre_categoria` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bazar`.`PRODUCTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bazar`.`PRODUCTOS` (
  `id_producto` INT(5) NOT NULL AUTO_INCREMENT,
  `codigo_producto` VARCHAR(45) NOT NULL,
  `nombre_producto` VARCHAR(40) NOT NULL,
  `precio_producto` INT(6) NOT NULL,
  `marca_FK` INT(2) NOT NULL,
  `usuario_FK` INT(2) NOT NULL,
  `categoria_FK` INT(2) NOT NULL,
  PRIMARY KEY (`id_producto`),
  INDEX `fk_PRODUCTOS_MARCAS1_idx` (`marca_FK` ASC) ,
  INDEX `fk_PRODUCTOS_USUARIOS1_idx` (`usuario_FK` ASC) ,
  INDEX `fk_PRODUCTOS_CATEGORIAS1_idx` (`categoria_FK` ASC) ,
  CONSTRAINT `fk_PRODUCTOS_MARCAS1`
    FOREIGN KEY (`marca_FK`)
    REFERENCES `bazar`.`MARCAS` (`id_marca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRODUCTOS_USUARIOS1`
    FOREIGN KEY (`usuario_FK`)
    REFERENCES `bazar`.`USUARIOS` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRODUCTOS_CATEGORIAS1`
    FOREIGN KEY (`categoria_FK`)
    REFERENCES `bazar`.`CATEGORIAS` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bazar`.`VENTAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bazar`.`VENTAS` (
  `id_venta` INT NOT NULL AUTO_INCREMENT,
  `fecha_emcion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `cliente_FK` INT NOT NULL,
  `usuario_FK` INT(2) NOT NULL,
  PRIMARY KEY (`id_venta`),
  INDEX `fk_VENTAS_CLIENTES1_idx` (`cliente_FK` ASC) ,
  INDEX `fk_VENTAS_USUARIOS1_idx` (`usuario_FK` ASC) ,
  CONSTRAINT `fk_VENTAS_CLIENTES1`
    FOREIGN KEY (`cliente_FK`)
    REFERENCES `bazar`.`CLIENTES` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VENTAS_USUARIOS1`
    FOREIGN KEY (`usuario_FK`)
    REFERENCES `bazar`.`USUARIOS` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bazar`.`FACTURAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bazar`.`FACTURAS` (
  `id_factura` INT NOT NULL AUTO_INCREMENT,
  `total_factura` INT(7) NOT NULL,
  `venta_FK` INT NOT NULL,
  PRIMARY KEY (`id_factura`),
  INDEX `fk_FACTURAS_VENTAS1_idx` (`venta_FK` ASC) ,
  CONSTRAINT `fk_FACTURAS_VENTAS1`
    FOREIGN KEY (`venta_FK`)
    REFERENCES `bazar`.`VENTAS` (`id_venta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bazar`.`DETALLE_FACTURAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bazar`.`DETALLE_FACTURAS` (
  `id_detalle_factura` INT NOT NULL AUTO_INCREMENT,
  `cantidad` INT(3) NOT NULL,
  `total` INT(7) NOT NULL,
  `producto_FK` INT(5) NOT NULL,
  `factura_FK` INT NOT NULL,
  PRIMARY KEY (`id_detalle_factura`),
  INDEX `fk_DETALLE_COMPRA_PRODUCTOS1_idx` (`producto_FK` ASC) ,
  INDEX `fk_DETALLE_COMPRA_FACTURAS1_idx` (`factura_FK` ASC) ,
  CONSTRAINT `fk_DETALLE_COMPRA_PRODUCTOS1`
    FOREIGN KEY (`producto_FK`)
    REFERENCES `bazar`.`PRODUCTOS` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DETALLE_COMPRA_FACTURAS1`
    FOREIGN KEY (`factura_FK`)
    REFERENCES `bazar`.`FACTURAS` (`id_factura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bazar`.`BOLETAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bazar`.`BOLETAS` (
  `id_boleta` INT NOT NULL AUTO_INCREMENT,
  `total_boleta` INT(7) NOT NULL,
  `venta_FK` INT NOT NULL,
  PRIMARY KEY (`id_boleta`),
  INDEX `fk_BOLETAS_VENTAS1_idx` (`venta_FK` ASC) ,
  CONSTRAINT `fk_BOLETAS_VENTAS1`
    FOREIGN KEY (`venta_FK`)
    REFERENCES `bazar`.`VENTAS` (`id_venta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bazar`.`DETALLE_BOLETAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bazar`.`DETALLE_BOLETAS` (
  `id_detalle_boleta` INT NOT NULL AUTO_INCREMENT,
  `cantidad` INT(3) NOT NULL,
  `total` INT(7) NOT NULL,
  `producto_FK` INT(5) NOT NULL,
  `boleta_FK` INT NOT NULL,
  PRIMARY KEY (`id_detalle_boleta`),
  INDEX `fk_DETALLE_COMPRA_PRODUCTOS1_idx` (`producto_FK` ASC) ,
  INDEX `fk_DETALLE_BOLETAS_BOLETAS1_idx` (`boleta_FK` ASC) ,
  CONSTRAINT `fk_DETALLE_COMPRA_PRODUCTOS10`
    FOREIGN KEY (`producto_FK`)
    REFERENCES `bazar`.`PRODUCTOS` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DETALLE_BOLETAS_BOLETAS1`
    FOREIGN KEY (`boleta_FK`)
    REFERENCES `bazar`.`BOLETAS` (`id_boleta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bazar`.`DATOS_EMPRESA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bazar`.`DATOS_EMPRESA` (
  `id_datos_empresa` INT NOT NULL AUTO_INCREMENT,
  `nombre_empresa` VARCHAR(40) NOT NULL,
  `rut_empresa` VARCHAR(10) NOT NULL,
  `direccion_empresa` VARCHAR(64) NOT NULL,
  `IVA` INT NOT NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`id_datos_empresa`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- -----------------------------------------------------
-- Insert Roles
-- -----------------------------------------------------
INSERT INTO `bazar`.`ROLES` (`rol_usuario`) VALUES
('JEFE DE VENTAS'),
('VENDEDOR');
-- -----------------------------------------------------
-- Insert Regiones
-- -----------------------------------------------------
INSERT INTO `bazar`.`REGIONES` (`nombre_region`) VALUES
('BIOBIO'),
('ÑUBLE'),
('CONCEPCIÓN'),
('MAULE'),
('ARAUCANÍA');
-- -----------------------------------------------------
-- Insert Comunas
-- -----------------------------------------------------
INSERT INTO `bazar`.`COMUNAS` (`nombre_comuna`, `region_FK`) VALUES
('CONCEPCION', 1),
('LOS ANGELES', 1),
('CHILLAN', 2),
('TEMUCO', 2),
('PUERTO MONTT', 3),
('VALDIVIA', 3),
('VINA DEL MAR', 4),
('VALPARAISO', 4),
('SANTIAGO', 5),
('RANCAGUA', 5);
-- -----------------------------------------------------
-- Insert Usuarios
-- -----------------------------------------------------
INSERT INTO `bazar`.`USUARIOS` (`run_usuario`, `clave_usuario`, `nombre_usuario`, `apellido_usuario`, `rol_FK`, `comuna_FK`) VALUES
('18505240-0', 'PASS1234', 'FERNANDO', 'ROSAS', 1, 3),
('12345678-9', 'PASS1234', 'JUAN', 'PEREZ', 2, 3),
('98765432-1', 'PASS1234', 'MARIA', 'LOPEZ', 2, 3),
('12345678-K', 'PASS1234', 'PEDRO', 'GARCIA', 2, 3),
('1234567-8', 'PASS1234', 'ANA', 'MARTINEZ', 2, 3);
-- -----------------------------------------------------
-- Insert Tipo Giro
-- -----------------------------------------------------
INSERT INTO `bazar`.`TIPO_GIRO` (`nombre_giro`) VALUES
('MAYORISTA'),
('MINORISTA');
-- -----------------------------------------------------
-- Insert Razon Social
-- -----------------------------------------------------
INSERT INTO `bazar`.`RAZON_SOCIAL` (`razon_social`) VALUES
('NO TIENE'),
('TECHNEXUS GROUP LTD'),
('INNOVATECH SOLUTIONS CORP');
-- -----------------------------------------------------
-- Insert Clientes
-- -----------------------------------------------------
INSERT INTO `bazar`.`CLIENTES` (`run_cliente`, `nombre_cliente`, `apellido_cliente`, `direccion`, `comuna_FK`, `tipo_giro_FK`, `razon_social_FK`, `usuario_FK`) VALUES
('20512977-1', 'ELIZABETH', 'CUEVAS', 'DIREC2312', 3, 2, 2, 2),
('19415787-2', 'JORGE', 'MATTIONI', 'DIREC9084', 3, 1, 2, 2),
('17682634-3', 'LUNA', 'ARRIAGADA', 'CALLE2034', 2, 2, 2, 3),
('207425912-0', 'ALBERTO', 'QUINTEROS', 'CALLE322', 1, 1, 1, 3),
('17727812-5', 'JULIA', 'ACUÑA', 'DIREC22', 6, 2, 3, 4),
('18626384-9', 'ROCIO', 'ZUÑIGA', 'DIREC726', 9, 1, 1, 4),
('20233902-2', 'CARLA', 'AVILA', 'DIREC221', 7, 1, 1, 4),
('16243683-3', 'ALYSSA', 'ARAYA', 'CALLE473', 10, 2, 3, 2),
('16326897-1', 'LIAM', 'CADIZ', 'DIRECT9282', 1, 2, 3, 5),
('17633922-2', 'AGUSTIN', 'ROSAS', 'CALLE2233', 2, 1, 1, 5);
-- -----------------------------------------------------
-- Insert Marcas
-- -----------------------------------------------------
INSERT INTO `bazar`.`MARCAS` (`nombre_marca`) VALUES
('LOGITEC'),
('SONY'),
('PHILIPS'),
('JBL'),
('MONSTER'),
('SAMSUNG'),
('HP'),
('DELL');
-- -----------------------------------------------------
-- Insert Categorias
-- -----------------------------------------------------
INSERT INTO `bazar`.`CATEGORIAS` (`nombre_categoria`) VALUES
('TECLADOS'),
('AUDIFONOS'),
('MOUSE'),
('PARLANTES'),
('MONITORES');
-- -----------------------------------------------------
-- Insert Productos
-- -----------------------------------------------------
INSERT INTO `bazar`.`PRODUCTOS` (`codigo_producto`, `nombre_producto`, `precio_producto`, `marca_FK`, `usuario_FK`, `categoria_FK`) VALUES
('97656', 'AUDIFONOS INALAMBRICOS', 29990, 4, 1, 2),
('87623', 'MOUSE ERGONOMICO', 10990, 1, 1, 3),
('12462', 'PARLANTE INFANTIL', 11990, 2, 1, 4),
('82346', 'TECLADO OFICINA', 9990, 1, 1, 1),
('44832', 'MOUSE INALAMBRICO', 6999, 5, 1, 3),
('12345', 'MONITOR DEPREDADOR', 19990, 8, 1, 5),
('123456', 'MONITOR NORMAL', 26999, 7, 1, 5);
-- -----------------------------------------------------
-- Insert ventas
-- -----------------------------------------------------
INSERT INTO `bazar`.`VENTAS` (`fecha_emcion`, `cliente_FK`, `usuario_FK`) VALUES 
('2023-06-01 09:00:00', 1, 2),
('2023-06-02 14:30:00', 2, 2),
('2023-06-03 11:45:00', 2, 2),
('2023-06-04 16:20:00', 2, 2),
('2023-06-05 10:15:00', 3, 3),
('2023-06-06 13:45:00', 4, 3),
('2023-06-07 15:30:00', 4, 4),
('2023-06-08 12:10:00', 5, 4),
('2023-06-09 10:45:00', 5, 5),
('2023-06-10 17:00:00', 10, 5);
-- -----------------------------------------------------
-- Insert facturas
-- -----------------------------------------------------
INSERT INTO `bazar`.`FACTURAS` (`total_factura`, `venta_FK`) VALUES 
((29990 * 2), 1),
(((10990 * 3) + (11990 * 1) ), 2),
(((29990 * 2) + (10990 * 1) + (11990 * 1) ), 3),
((29990 * 2), 4),
(((10990 * 5) + (11990 * 2)), 5);
-- -----------------------------------------------------
-- Insert boletas
-- -----------------------------------------------------
INSERT INTO `bazar`.`BOLETAS` (`total_boleta`, `venta_FK`) VALUES 
((29990 * 2), 6),
(((10990 * 3) + (11990 * 1) ), 7),
(((29990 * 2) + (10990 * 1) + (11990 * 1) ), 8),
((29990 * 2), 9),
(((10990 * 5) + (11990 * 2)), 10);
-- -----------------------------------------------------
-- Insert Detalle Boletas
-- -----------------------------------------------------
INSERT INTO `bazar`.`DETALLE_FACTURAS` (`cantidad`, `total`, `producto_FK`, `factura_FK`) VALUES 
(2,(29990 * 2) , 1, 1),
(3,(10990 * 3) , 2, 2),
(1,(11990 * 1) , 3, 2),
(2,(29990 * 2) , 1, 3),
(1,(10990 * 1) , 2, 3),
(1,(11990 * 1) , 3, 3),
(2,(29990 * 2) , 1, 4),
(5,(10990 * 5) , 2, 5),
(2,(11990 * 2) , 3, 5);
-- -----------------------------------------------------
-- Insert Detalle Boletas
-- -----------------------------------------------------
INSERT INTO `bazar`.`DETALLE_BOLETAS` (`cantidad`, `total`, `producto_FK`, `boleta_FK`) VALUES 
(2,(29990 * 2) , 1, 1),
(3,(10990 * 3) , 2, 2),
(1,(11990 * 1) , 3, 2),
(2,(29990 * 2) , 1, 3),
(1,(10990 * 1) , 2, 3),
(1,(11990 * 1) , 3, 3),
(2,(29990 * 2) , 1, 4),
(5,(10990 * 5) , 2, 5),
(2,(11990 * 2) , 3, 5);
-- -----------------------------------------------------
-- Procedimiento almacenado para generar una venta, boleta o factura
-- -----------------------------------------------------
DELIMITER $
-- Procedimiento almacenado para generar una venta, boleta o factura
CREATE PROCEDURE generar_venta(id_cliente INT, id_vendedor INT, generar_venta INT)
BEGIN
    -- Declaracion de Variables
    DECLARE id_ultima_venta INT;
    DECLARE id_ultima_boleta INT;
    DECLARE id_ultima_factura INT;
    DECLARE total_boleta_compra INT;
    DECLARE total_factura_compra INT;

    -- Crear la venta
    INSERT INTO ventas (cliente_FK, usuario_FK) VALUES (id_cliente, id_vendedor);
    SET id_ultima_venta = LAST_INSERT_ID();

    IF generar_venta = 1 THEN
        -- Crear la boleta
        INSERT INTO boletas (venta_FK) VALUES (id_ultima_venta);
        SET id_ultima_boleta = LAST_INSERT_ID();

        -- Insertar detalles de la boleta desde la tabla temporal
        INSERT INTO detalle_boletas (cantidad, total, producto_FK, boleta_FK)
        SELECT cantidad, total_producto, id_producto, (id_ultima_boleta) AS boleta_FK FROM detalle_temp;

        -- Calcular el total de la boleta
        SELECT SUM(total_producto) INTO total_boleta_compra FROM detalle_temp;
        UPDATE boletas SET total_boleta = total_boleta_compra WHERE id_boleta = id_ultima_boleta;

        -- Borrar la tabla temporal
        TRUNCATE TABLE detalle_temp;

        -- Devolver la boleta creada
        SELECT b.id_boleta, b.total_boleta, DATE(v.fecha_emcion) AS fecha_emision
        FROM boletas AS b
        INNER JOIN ventas AS v ON b.venta_FK = v.id_venta
        WHERE b.id_boleta = id_ultima_boleta;

        -- Devolver el detalle de la boleta creada
        SELECT d.cantidad, d.total, p.codigo_producto, p.nombre_producto, p.precio_producto  
        FROM detalle_boletas AS d
        INNER JOIN productos AS p
        ON d.producto_FK = p.id_producto
        WHERE boleta_FK = id_ultima_boleta;

    ELSE
        -- Crear la factura
        INSERT INTO facturas (venta_FK) VALUES (id_ultima_venta);
        SET id_ultima_factura = LAST_INSERT_ID();

        -- Insertar detalles de la factura desde la tabla temporal
        INSERT INTO detalle_facturas (cantidad, total, producto_FK, factura_FK)
        SELECT cantidad, total_producto, id_producto, (id_ultima_factura) AS factura_FK FROM detalle_temp;

        -- Calcular el total de la factura
        SELECT SUM(total_producto) INTO total_factura_compra FROM detalle_temp;
        UPDATE facturas SET total_factura = total_factura_compra WHERE id_factura = id_ultima_factura;

        -- Borrar la tabla temporal
        TRUNCATE TABLE detalle_temp;

        -- Devolver la factura creada
        SELECT f.id_factura, f.total_factura, DATE(v.fecha_emcion) AS fecha_emision
        FROM facturas AS f
        INNER JOIN ventas AS v ON f.venta_FK = v.id_venta
        WHERE f.id_factura = id_ultima_factura;

        -- Devolver el detalle de la factura creada
        SELECT d.cantidad, d.total, p.codigo_producto, p.nombre_producto,p.precio_producto  
        FROM detalle_facturas AS d
        INNER JOIN productos AS p
        ON d.producto_FK = p.id_producto
        WHERE factura_FK = id_ultima_factura;

    END IF;
END$
DELIMITER ;
-- -----------------------------------------------------
-- Procedimiento almacenado para tabla para clientes
-- -----------------------------------------------------
DELIMITER $

CREATE PROCEDURE traer_tablas_cliente()
BEGIN
    SELECT nombre_giro FROM tipo_giro;
    SELECT razon_social FROM razon_social WHERE id_razon_social != 1;
    SELECT nombre_comuna FROM comunas;

END$
DELIMITER ;
-- -----------------------------------------------------
-- Procedimiento almacenado para insertar nuevo cliente
-- -----------------------------------------------------
DELIMITER $
-- Procedimiento almacenado para insertar nuevo cliente
CREATE PROCEDURE registro_cliente(
    p_run_cliente VARCHAR(10),
    p_nombre_cliente VARCHAR(25),
    p_apellido_cliente VARCHAR(25),
    p_direccion VARCHAR(64),
    p_nombre_giro VARCHAR(30),
    p_razon_social VARCHAR(45),
    p_nombre_comuna VARCHAR(30),
    p_id_vendedor INT
)
BEGIN
    DECLARE v_id_comuna INT;
    DECLARE v_id_giro INT;
    DECLARE v_id_razon_social INT;
    DECLARE v_id_cliente INT;

    -- Obtener el ID de la comuna
    SELECT id_comuna INTO v_id_comuna
    FROM COMUNAS
    WHERE nombre_comuna = p_nombre_comuna;

    -- Obtener el ID del giro
    SELECT id_giro INTO v_id_giro
    FROM TIPO_GIRO
    WHERE nombre_giro = p_nombre_giro;

    -- Verificar si la razón social existe
    SELECT id_razon_social INTO v_id_razon_social
    FROM RAZON_SOCIAL
    WHERE razon_social = p_razon_social;

    -- Si la razón social no existe, agregarla
    IF v_id_razon_social IS NULL THEN
        START TRANSACTION;
        
        INSERT INTO RAZON_SOCIAL (razon_social)
        VALUES (p_razon_social);

        SET v_id_razon_social = LAST_INSERT_ID();

        COMMIT;
    END IF;

    START TRANSACTION;

    -- Insertar el cliente en la tabla CLIENTES
    INSERT INTO CLIENTES (run_cliente, nombre_cliente, apellido_cliente, direccion, comuna_FK, tipo_giro_FK, razon_social_FK, usuario_FK)
    VALUES (p_run_cliente, p_nombre_cliente, p_apellido_cliente, p_direccion, v_id_comuna, v_id_giro, v_id_razon_social, p_id_vendedor);

    SET v_id_cliente = LAST_INSERT_ID();

    COMMIT;

    SELECT cl.id_cliente, cl.run_cliente, cl.nombre_cliente, cl.apellido_cliente, e.razon_social, t.nombre_giro, cl.direccion, c.nombre_comuna, r.nombre_region 
    FROM CLIENTES AS cl 
    INNER JOIN RAZON_SOCIAL AS e 
        ON cl.razon_social_FK = e.id_razon_social 
    INNER JOIN TIPO_GIRO AS t 
        ON cl.tipo_giro_FK = t.id_giro 
    INNER JOIN COMUNAS AS c 
        ON cl.comuna_FK = c.id_comuna 
    INNER JOIN REGIONES AS r 
        ON c.region_FK = r.id_regiones 
    WHERE cl.id_cliente = v_id_cliente;
END $

DELIMITER ;
